// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqodscwcdhlrwowwdshr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhxb2RzY3djZGhscndvd3dkc2hyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NTA5ODksImV4cCI6MjA2NzMyNjk4OX0.9HUdMCQE9jYPtU8eWnIkD6NrD7SMVDafq5yR7T_B_Zc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});